# Generated by Django 4.2.7 on 2023-11-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_type',
            new_name='review_text',
        ),
    ]
